account/urls.py
from django.urls import path, include
from django.contrib.auth.views import login, logout
from account import views

app_name = "account"

urlpatterns = [
    path('login/', login, {'template_name': 'account/login.html'}, name='login'),
    path('logout/', logout, {'template_name': 'account/logout.html'}, name='logout'),
    path('register/', views.register, name='register'),
    path('login_success/', views.login_success, name='login_success'),
    path('logout_success/', views.logout_success, name='logout_success'),
    path('register_success/', views.register_success, name='register_success'),
    path('not_verified/', views.not_verified, name='not_verified'),
    path('login_next_test/', views.login_next_test, name='login_next_test'),
    path('verify/(?P<user>.*)/(?P<code>.*)/', views.verify, name='verify'),
    path('verify/', views.verify, {'code': None, 'user': None}, name='verify')
]

blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = "blog"

urlpatterns = [

    # Site Nav

    path('', views.post_list, name='index'),
    # path(r'^api/', views.api_root, name='api'),
    # path('post/pk/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    # path('post/<int:pk>/comment_reply/', views.comment_reply, name='comment_reply'),
    # re_path(r'^post/edit/(?P<pk>\d+)/$', views.post_edit, name='post_edit'),
    # path(r'^categories/add/$', views.add_categories, name='add_categories'),
    # path(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    # path(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    # path(r'^post/remove-all/$', views.post_remove_all, name='post_remove_all'),
    # path(r'^post/category/(?P<pk>\d+)/$', views.cat_post, name='cat_post'),
    # path(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    # path(r'^comment/(?P<pk>\d+)/remove/main/$', views.comment_remove_main, name='comment_remove_main'),
]

blogV2/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.post_list, name='index'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('data/', include('dataAnalysis.urls', namespace='dataAnalysis')),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('comments', include('django_comments.urls'))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from ckeditor.fields import RichTextField
# from mptt.models import MPTTModel, TreeForeignKey


# class Comment(MPTTModel):
#     name = models.CharField(max_length=50, unique=True)
#     parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

#     class MPTTMeta:
#         order_insertion_by = ['name']  


class Categories(models.Model):
    title = models.CharField(max_length=65)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=155)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category', args=[str(self.slug)])

    class Meta:
        verbose_name_plural = 'Categories'


class BlogType(models.Model):
    type_title = models.CharField(max_length=100, default='Default')
    description = models.TextField(max_length=155)

    def __str__(self):
        return self.type_title


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    type = models.ForeignKey(BlogType, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Categories, related_name='categories')
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=False, null=True, blank=True)
    text = RichTextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published = models.BooleanField(default=False)
    published_date = models.DateTimeField(
            blank=True, null=True)
    modified = models.DateTimeField(auto_now=True, blank=True, null=True)

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def publish(self):
        self.published_date = timezone.now()
        self.published = True
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', args=[str(self.slug)])

blog/forms.py
from django import forms
from .models import Post, Categories
from ckeditor.widgets import CKEditorWidget
from functools import partial
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Submit


DateInput = partial(forms.DateInput, {'id': 'datepicker'})


class PostForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = ('title', 'type', 'categories', 'text',)


class CategoriesForm(forms.ModelForm):

    class Meta:
        model = Categories
        fields = ('title', 'slug', 'description')

blog/views.py
from django.shortcuts import render, render_to_response, get_object_or_404, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.utils import timezone
from .models import Post, User, Categories, BlogType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.template import RequestContext, loader
from .forms import PostForm, CategoriesForm

from django.contrib import messages


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    user = request.user
    cat_list_side = Categories.objects.all()
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/index.html', locals())


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.publish()
            post.save()
            form.save_m2m()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_create.html', locals())


def post_detail(request, pk):
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        raise Http404("Unable to load post id: " + post.id)

    return render(request, 'blog/post_detail.html', locals())


@login_required
def post_edit(request, pk):
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        raise Http404("Unable to load post id: " + post.id)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', locals())

templates/blog/index.html
{% extends "base.html" %}

{% block content %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md">
                {% if posts %}
                <nav>
                    <ul class="pagination">
                        {% if posts.has_previous %}
                            <li class="page-item">
                                <a href="?page={{ posts.previous_page_number }}" class="page-link">
                                    <i class="far fa-caret-square-left"></i> Newer
                                </a>
                            </li>
                        {% endif %}
                        {% if posts.has_next %}
                            <li class="page-item">
                                <a href="?page={{ posts.next_page_number }}" class="page-link">Older 
                                    <i class="far fa-caret-square-right"></i>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                    <ul class="pagination">
                        <li class="pagination">
                                Page {{ posts.number }} of {{ posts.paginator.num_pages }}
                        </li>
                    </ul>
                </nav>
                    {% for post in posts %}
                        {% if post.published == True %}
                            <div class="card">
                                <div class="card-header">
                                    <h5 class="card-title">{{ post.title }}</h5>
                                </div>
                                <div class="card-body">
                                    <hr style="width:75%;"/>
                                    <p class="card-text">{{ post.text|safe|linebreaks|truncatechars:300 }} 
                                        <a href="{% url 'blog:post_detail' pk=post.pk %}" class="custom">
                                            <i><small>Click to read full post</small></i>
                                        </a>
                                    </p> 
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <p>No Posts :(</p>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock content %}

templates/blog/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block content %}
    <main role="main" class="container">
        <div class="card">
            <div class="card-body">
                <form action="{% url 'blog:post_new' %}" method="POST" class="post-form">{% csrf_token %}
                    {{ form.media }}
                    {{ form|crispy }}
                    <hr />
                    <button type="submit" class="save btn btn-dark">Post</button>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}


{% block content %}
    <main role="main" class="container">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">{{ post.title }}</h5>
            </div>
            <div class="card-body">
                <hr style="width:75%;"/>
                <p class="card-text">{{ post.text|safe|linebreaks }}</p>
                <hr style="width:75%;"/>
                <p class="card-text"><i><small><b>Last Modified:</b> {{ post.modified|timesince }} ago</small></i></p>
                <p class="card-text"><i><small><b>Published:</b> {{ post.created_date|timesince }} ago</small></i></p>
                <br />
                <!-- <button type="button" class="btn btn-success" id="add_comment">
                    Show Comments <i class="fas fa-angle-down"></i>
                </button> -->
                {% if user.is_authenticated %}
                    {% if user == post.author %}
                        <a class="btn btn-info"
                            href="{% url 'blog:post_edit' pk=post.pk %}"
                            data-toggle="tooltip" data-placement="top" title="Edit Post">
                            <i class="far fa-edit"></i>
                        </a>
                    {% endif %}
                {% endif %}
            </div>
        </div>

        <div class="card" id="comments">
            <div class="card-body">
                <div id="disqus_thread"></div>
                <script>
                
                /**
                *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
                /**/
                var disqus_config = function () {
                this.page.url ="{{ request.build_absolute_uri }}";  // Replace PAGE_URL with your page's canonical URL variable
                this.page.identifier = "{{ post.id }}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                };
                
                (function() { // DON'T EDIT BELOW THIS LINE
                var d = document, s = d.createElement('script');
                s.src = 'https://randomnation-1.disqus.com/embed.js';
                s.setAttribute('data-timestamp', +new Date());
                (d.head || d.body).appendChild(s);
                })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                <!-- <div class="fb-comments" data-href="{{ post.get_absolute_uri }}" data-numposts="5" data-width="100%" data-colorscheme="dark"></div> -->
            </div>
        </div>
        
    </main>
{% endblock %}

templates/blog/post_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block content %}
    <main role="main" class="container">
        <div class="card">
            <div class="card-body">
                <form action="{% url 'blog:post_edit' pk=post.pk %}" method="POST" class="post-form">{% csrf_token %}
                    {{ form.media }}
                    {{ form|crispy }}
                    <hr />
                    <button type="submit" class="save btn btn-dark">Update</button>
                </form>
            </div>
        </div>
    </main>
{% endblock %}