account/urls.py
from django.urls import path, include
from django.contrib.auth.views import login, logout
from account import views

app_name = "account"

urlpatterns = [
    path('login/', login, {'template_name': 'account/login.html'}, name='login'),
    path('logout/', logout, {'template_name': 'account/logout.html'}, name='logout'),
    path('register/', views.register, name='register'),
    path('login_success/', views.login_success, name='login_success'),
    path('logout_success/', views.logout_success, name='logout_success'),
    path('register_success/', views.register_success, name='register_success'),
    path('not_verified/', views.not_verified, name='not_verified'),
    path('login_next_test/', views.login_next_test, name='login_next_test'),
    path('verify/(?P<user>.*)/(?P<code>.*)/', views.verify, name='verify'),
    path('verify/', views.verify, {'code': None, 'user': None}, name='verify')
]

blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = "blog"

urlpatterns = [

    # Site Nav

    path('', views.post_list, name='index'),
    # path(r'^api/', views.api_root, name='api'),
    # path('post/pk/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    # path('post/<int:pk>/comment_reply/', views.comment_reply, name='comment_reply'),
    # re_path(r'^post/edit/(?P<pk>\d+)/$', views.post_edit, name='post_edit'),
    # path(r'^categories/add/$', views.add_categories, name='add_categories'),
    # path(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    # path(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    # path(r'^post/remove-all/$', views.post_remove_all, name='post_remove_all'),
    # path(r'^post/category/(?P<pk>\d+)/$', views.cat_post, name='cat_post'),
    # path(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    # path(r'^comment/(?P<pk>\d+)/remove/main/$', views.comment_remove_main, name='comment_remove_main'),
]

blogV2/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.post_list, name='index'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('data/', include('dataAnalysis.urls', namespace='dataAnalysis')),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('comments', include('django_comments.urls'))
]

dataAnalysis/urls.py
from django.urls import path, re_path
from dataAnalysis import views

app_name = "dataAnalysis"

urlpatterns = [
    path('heatmap/', views.heatmap_index, name='comment_heatmap')
    # path('user/<int:pk>/update/', views.user_profile_edit, name='update_profile'),
]

profiles/urls.py
from django.urls import path, re_path
from profiles import views

app_name = "profiles"

urlpatterns = [
    path('user/<int:pk>/', views.user_profile, name='user_profile'),
    path('user/<int:pk>/update/', views.user_profile_edit, name='update_profile'),
]

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Blog V2">
    <meta name="author" content="Jason">
    <link rel="icon" href="#">

    <title>Portfolio</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'blog:index' %}">Randomnation</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:index' %}">Blog <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dataAnalysis:comment_heatmap' %}">
                            <i class="fas fa-chart-bar"></i> Data Analysis <span class="sr-only">(current)</span>
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post_new' %}"><i class="far fa-edit"></i> Add New Post</a>
                </li>
                
            {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile:user_profile' pk=user.id %}">Profile</a>
                </li>
                {% if user.is_superuser %}
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:login' %}">Login/Register</a>
                </li>
            {% endif %}            
        </ul>
        <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" 
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" 
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
        crossorigin="anonymous"></script>
    <script src="{% static 'js/fontawesome-all.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script id="dsq-count-scr" src="//randomnation-1.disqus.com/count.js" async></script>
  </body>
</html>