account/urls.py
from django.urls import path, include
from django.contrib.auth.views import login, logout
from account import views

app_name = "account"

urlpatterns = [
    path('login/', login, {'template_name': 'account/login.html'}, name='login'),
    path('logout/', logout, {'template_name': 'account/logout.html'}, name='logout'),
    path('register/', views.register, name='register'),
    path('login_success/', views.login_success, name='login_success'),
    path('logout_success/', views.logout_success, name='logout_success'),
    path('register_success/', views.register_success, name='register_success'),
    path('not_verified/', views.not_verified, name='not_verified'),
    path('login_next_test/', views.login_next_test, name='login_next_test'),
    path('verify/(?P<user>.*)/(?P<code>.*)/', views.verify, name='verify'),
    path('verify/', views.verify, {'code': None, 'user': None}, name='verify')
]

blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = "blog"

urlpatterns = [

    # Site Nav

    path('', views.post_list, name='index'),
    # path(r'^api/', views.api_root, name='api'),
    # path('post/pk/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    # path('post/<int:pk>/comment_reply/', views.comment_reply, name='comment_reply'),
    # re_path(r'^post/edit/(?P<pk>\d+)/$', views.post_edit, name='post_edit'),
    # path(r'^categories/add/$', views.add_categories, name='add_categories'),
    # path(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    # path(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    # path(r'^post/remove-all/$', views.post_remove_all, name='post_remove_all'),
    # path(r'^post/category/(?P<pk>\d+)/$', views.cat_post, name='cat_post'),
    # path(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    # path(r'^comment/(?P<pk>\d+)/remove/main/$', views.comment_remove_main, name='comment_remove_main'),
]

blogV2/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.post_list, name='index'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('data/', include('dataAnalysis.urls', namespace='dataAnalysis')),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('comments', include('django_comments.urls'))
]

profiles/urls.py
from django.urls import path, re_path
from profiles import views

app_name = "profiles"

urlpatterns = [
    path('user/<int:pk>/', views.user_profile, name='user_profile'),
    path('user/<int:pk>/update/', views.user_profile_edit, name='update_profile'),
]

profiles/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    homepage = models.URLField('Website', blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    gamer_tag = models.CharField(max_length=200, blank=True)
    forum_sig = models.CharField(max_length=200, blank=True)

    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    post_save.connect(create_user_profile, sender=User)

    def __unicode__(self):
        return 'Profile of user: {}'.format(self.user.username)

profiles/forms.py
from django import forms
from .models import UserProfile
from functools import partial


DateInput = partial(forms.DateInput, {'id': 'datepicker'})


class ProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=DateInput())

    class Meta:
        model = UserProfile
        fields = {'bio', 'homepage', 'gamer_tag', 'date_of_birth', }

profiles/views.py
import django.shortcuts
from .models import UserProfile
from .forms import ProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def index(request):
    return django.shortcuts.render(request, 'profiles/index.html', locals())


@login_required
def user_profile(request, pk):
    profile = django.shortcuts.get_object_or_404(UserProfile, pk=pk)
    return django.shortcuts.render(request, 'profiles/profile.html', locals())


@login_required
def user_profile_edit(request, pk):
    profile = django.shortcuts.get_object_or_404(UserProfile, pk=pk)
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                'Success! Your profile has been updated!',
                extra_tags='profile')
            return django.shortcuts.redirect('profiles:user_profile', pk=profile.pk)
    else:
        form = ProfileForm(instance=profile)
    return django.shortcuts.render(request, 'profiles/profile_edit.html', locals())

templates/profiles/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <main role="main" class="container">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <div class="card-heading">
                        <h3 class="card-title">{{ user.first_name }} {{ user.last_name }}</h3>
                    </div>
                    <div class="media">
                            <img class="align-self-start mr-3" alt="{{ user.username }}" src="https://s.gravatar.com/avatar/a8c69c811defeee6b4c78cb1ca90b395?s=300"
                                class="img-circle img-responsive">
                            <div class="media-body">
                              <h5 class="mt-0">Top-aligned media</h5>
                              <p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
                              <p>Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                            </div>
                          </div>
                    <!-- <div class="row">
                        <div class="col-md-3 col-lg-3 " align="center">
                            <img alt="User Pic" src="https://s.gravatar.com/avatar/a8c69c811defeee6b4c78cb1ca90b395?s=300"
                                class="img-circle img-responsive">
                        </div>
                        <div class=" col-md-9 col-lg-9 ">
                            <table class="table table-user-information">
                                <tbody>
                                <tr>
                                    <td>Gamertag:</td>
                                    <td>{{ user.profile.gamer_tag }}</td>
                                </tr>
                                <tr>
                                    <td>Joined date:</td>
                                    <td>{{ user.date_joined }}</td>
                                </tr>
                                <tr>
                                    <td>Date of Birth</td>
                                    <td>{{ user.profile.date_of_birth }}</td>
                                </tr>

                                <tr>
                                <tr>
                                    <td>Gender</td>
                                    <td>Male</td>
                                </tr>
                                <tr>
                                    <td>Homepage</td>
                                    <td><a href="{{ user.profile.homepage }}">{{ user.profile.homepage }}</a></td>
                                </tr>
                                <tr>
                                    <td>Email</td>
                                    <td><a href="{{ user.email }}">{{ user.email }}</a></td>
                                </tr>
                                <tr>
                                    <td>About Me...</td>
                                    <td>{{ user.profile.bio }}</td>
                                </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'profiles:update_profile' pk=profile.pk %}"
                            class="btn btn-success">Edit Profile</a>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/profiles/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block content %}
    <div class="panel panel-primary">
        <div class="panel-body">
            <form action="{% url 'profiles:update_profile' pk=profile.pk %}" method="POST" class="post-form">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="panel-footer">
                    <button type="submit" class="save btn btn-default">Update</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}